### ISSUE TITLE
Don't use solid file on href attribute

### ISSUE THREAD

**Issue by muhibbudins** [YudiIrwanda/first#1]
Please see this line, href attribute must use valid link

https://github.com/YudiIrwanda/first/blob/7c4de9ca3547a760d57ccdeed2550e4a6e372cd5/latihan.html#L30

**Comment by YudiIrwanda** [comment]
Udah diganti ya di @5bf7cf8

**Comment by muhibbudins** [comment]
#5bf7cf8
